tap "armmbed/formulae", "https://github.com/ArmMbed/homebrew-formulae"
tap "homebrew-zathura/zathura", "https://github.com/homebrew-zathura/homebrew-zathura.git", trusted: true
# Library to render SVG files using Cairo
brew "librsvg"
# Arduino command-line interface
brew "arduino-cli"
# GNU compiler collection for arm-none-eabi
brew "arm-none-eabi-gcc"
# GNU debugger for arm-none-eabi cross development
brew "arm-none-eabi-gdb"
# Atmel AVR MCU programmer
brew "avrdude"
# Generate compilation database for clang tooling
brew "bear"
# Next-gen compiler infrastructure
brew "llvm"
# C/C++/ObjC language server
brew "ccls"
# Cross-platform make
brew "cmake"
# List system USB buses and devices
brew "cyme"
# Secure runtime for JavaScript and TypeScript
brew "deno"
# USB programmer
brew "dfu-util"
# Load/unload environment variables based on $PWD
brew "direnv"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU debugger
brew "gdb"
# GitHub command-line tool
brew "gh"
# OCR (Optical Character Recognition) engine
brew "tesseract"
# Distributed revision control system
brew "git"
# Configurable static site generator
brew "hugo"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Interactive computing in Python
brew "ipython"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Simple terminal UI for git commands
brew "lazygit"
# Clone of ls with colorful output, file type icons, and more
brew "lsd"
# Powerful, lightweight programming language
brew "lua"
# Language Server for the Lua language
brew "lua-language-server"
# Package manager for the Lua programming language
brew "luarocks"
# Language Server Protocol for Markdown
brew "marksman"
# Material Design theme for MkDocs
brew "mkdocs-material"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Port scanning utility for large networks
brew "nmap"
# Post-processing for scanned/photocopied books
brew "unpaper"
# Adds an OCR text layer to scanned PDF files
brew "ocrmypdf"
# On-chip debugging, in-system programming and boundary-scan testing
brew "open-ocd"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Your Gateway to Embedded Software Development Excellence
brew "platformio"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Tab completion for Python argparse
brew "python-argcomplete"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Generic machine emulator and virtualizer
brew "qemu"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Extremely fast Python linter, written in Rust
brew "ruff"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Bash syntax highlighter that encourages/fixes variables quoting
brew "shellharden"
# Cross-shell prompt for astronauts
brew "starship"
# STM32 discovery line Linux programmer
brew "stlink"
# Enables extra languages support for Tesseract
brew "tesseract-lang"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Parser generator tool
brew "tree-sitter-cli"
# List detailed info about USB devices
brew "usbutils"
# Command-line client for WebSockets
brew "websocat"
# Internet file retriever
brew "wget"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Interface library
brew "homebrew-zathura/zathura/girara", trusted: true
# Common components for zathura
brew "girara"
# PDF viewer
brew "homebrew-zathura/zathura/zathura"
# Poppler backend plugin for zathura
brew "homebrew-zathura/zathura/zathura-pdf-poppler"
# Enable Windows-like alt-tab
cask "alt-tab"
# Compact TeX distribution as alternative to the full TeX Live / MacTeX
cask "basictex"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Desktop automation application
cask "hammerspoon"
# Vector graphics editor
cask "inkscape"
# Keyboard customiser
cask "karabiner-elements"
# CP210x USB to UART Bridge VCP Driver
cask "silicon-labs-vcp-driver"
go "github.com/arduino/arduino-language-server"
cargo "cargo-binutils"
cargo "cargo-generate"
cargo "flip-link"
cargo "probe-run"
npm "corepack"
npm "typescript-language-server"
npm "typescript"
